baseURL = "https://spatialanalysis.github.io"
languageCode = "en-us"
title = "Learn Spatial Analysis | Center for Spatial Data Science"
theme = "hugo-smorg"
author = "Angela Li"
googleAnalytics = "UA-82228289-2"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishdir = "public"

copyright = "&copy; 2018 Center for Spatial Data Science"

[params]
  logofile = "csds_logo_white.png"
  logotype = "Center for Spatial Data Science" # in header and footer
  favicon = "favicon.png"
  homepgheader = "Learn Spatial Analysis"
  homepgsubheader = "Online resources, tutorials, and more"
  footer = "Follow us on [Twitter](https://twitter.com/GeoDaCenter) and [Facebook!](https://www.facebook.com/pg/geodacenter) <br />"
  subfooter = "Questions or comments? File an issue on [Github](https://github.com/spatialanalysis/spatialanalysis.github.io/issues)."

# Navigation Menu
# Note that secondary pages have a YAML header that indicates a parent page
[[menu.sectionmenu]]
  name = "Tutorials"
  url = "tutorials/"
  identifier = "tutorials"
  weight = 10  
  
[[menu.sectionmenu]]
  name = "Events"
  url = "events/"
  identifier = "events"
  weight = 20  
  
[[menu.sectionmenu]]
  name = "Workshop Schedule"
  url = "events/workshop-schedule/"
  parent = "events"
  weight = 201  
  
[[menu.sectionmenu]]
  name = "Links"
  url = "links/"
  identifier = "links"
  weight = 30 

[[menu.sectionmenu]]
  name = "About"
  url = "about/"
  identifier = "about"
  weight = 40

[[menu.sectionmenu]]
  name = "Blog"
  url = "post/"
  identifier = "post"
  weight = 50
  
